#!/usr/bin/env node
// Generates worker/src/lenses.generated.ts from reference/lens/*.md.
//
// A static import list is the only thing the Worker bundler can resolve, but the
// set of lenses varies per checkout: client packs are gitignored. So the list is
// generated from whatever is actually on disk, right before the build.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const lensDir = join(here, '../../reference/lens');
const out = join(here, '../src/lenses.generated.ts');

// Order the picker offers them in. Anything unlisted follows, alphabetically.
const ORDER = [];

const files = readdirSync(lensDir)
  .filter((f) => f.endsWith('.md') && f !== '_TEMPLATE.md')
  .sort((a, b) => {
    const ia = ORDER.indexOf(a.replace('.md', ''));
    const ib = ORDER.indexOf(b.replace('.md', ''));
    return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib) || a.localeCompare(b);
  });

/** First heading gives the name, first paragraph after "Who this lens is for" the blurb. */
function describe(md, id) {
  const heading = /^#\s+(?:Lens:\s*)?(.+)$/m.exec(md);
  const name = heading ? heading[1].trim() : id;
  const who = /##\s*Who this lens is for\s*\n+([\s\S]*?)(?:\n\s*\n|##)/.exec(md);
  const para = who ? who[1].replace(/\s+/g, ' ').trim() : '';
  // Cut on a sentence boundary, never mid-word.
  const sentences = para.match(/[^.]+\./g) ?? [para];
  let description = '';
  for (const sentence of sentences) {
    if ((description + sentence).length > 160) break;
    description += sentence;
  }
  description = (description || sentences[0] || '').trim();
  // A starter ships with Scout and describes a category, not a real product. The
  // picker says so, and offers to take the reader's own principles instead.
  return { name, description, starter: /^<!--\s*starter\b/m.test(md) };
}

/**
 * A lens may declare `<!-- extends: <id> -->`. House design principles hold across every
 * app in a company, while the persona, flows and calibration differ per app. So the shared
 * pack is written once and each app lens builds on it.
 */
function textFor(id, cache) {
  const md = cache[id];
  const base = /^<!--\s*extends:\s*([a-z0-9-]+)\s*-->/m.exec(md);
  if (!base || base[1] === id) return md;
  // A checkout may not carry the base pack. Build with what is here rather than failing.
  if (cache[base[1]] === undefined) {
    console.warn(`  note: ${id} extends ${base[1]}, which is not in this checkout`);
    return md;
  }
  return `${textFor(base[1], cache)}\n\n---\n\n${md}`;
}

const ident = (id) => `lens_${id.replace(/[^a-z0-9]/gi, '_')}`;

const imports = files.map((f) => `import ${ident(f.replace('.md', ''))} from '../../reference/lens/${f}';`);
const raw = Object.fromEntries(
  files.map((f) => [f.replace('.md', ''), readFileSync(join(lensDir, f), 'utf8')]),
);

// A pack another lens builds on is a building block, not something to pick. Whoever
// chooses the app lens already has it, so it stays out of the picker.
const bases = new Set(
  Object.values(raw)
    .map((md) => /^<!--\s*extends:\s*([a-z0-9-]+)\s*-->/m.exec(md)?.[1])
    .filter(Boolean),
);

const entries = files
  .filter((f) => !bases.has(f.replace('.md', '')))
  .map((f) => {
    const id = f.replace('.md', '');
    const { name, description, starter } = describe(raw[id], id);
    return { id, name, description, starter, text: textFor(id, raw) };
  });

writeFileSync(
  out,
  `// GENERATED by scripts/build-lenses.mjs. Do not edit.
// Add or remove a markdown file in reference/lens/ and rebuild.

${imports.join('\n')}

export interface LensInfo {
  id: string;
  name: string;
  description: string;
  /** Ships with Scout, describes a category rather than a real product. */
  starter: boolean;
}

export const LENS_TEXT: Record<string, string> = {
${entries
  .map((e) =>
    e.text === raw[e.id]
      ? `  '${e.id}': ${ident(e.id)},`
      : `  '${e.id}': [${JSON.stringify(
          `The active lens is "${e.name}". It is assembled from shared house principles first, ` +
            `then what this app adds on top. Report every lens finding under the active lens ` +
            `name, never under the name of the shared pack.`,
        )}, ${(/^<!--\s*extends:\s*([a-z0-9-]+)\s*-->/m.exec(raw[e.id]) ?? [])
          .slice(1)
          .map((b) => ident(b))
          .join(', ')}, ${ident(e.id)}].join('\\n\\n---\\n\\n'),`,
  )
  .join('\n')}
};

export const LENS_CATALOGUE: LensInfo[] = [
${entries
  .map(
    (e) =>
      `  { id: '${e.id}', name: ${JSON.stringify(e.name)}, description: ${JSON.stringify(e.description)}, starter: ${e.starter} },`,
  )
  .join('\n')}
];
`,
);

console.log(`lenses: ${entries.map((e) => e.id).join(', ') || 'none'}`);
